### ISSUE TITLE
Data path issue

### ISSUE THREAD

**Issue by Asraraf** [sunjesse/shape-attentive-unet#7]
Hi,
please provide the reasoning behind using "patient%03d/patient%03d_frame%02d"
As I'm using the Brain tumor dataset and I'm unable to give folder paths here.

Looking forward to your quick response.

**Comment by sunjesse** [comment]
Hi,

We used that formatting due to the structure of the AC17 dataset, which contains folders called "patientXXX" where XXX is a number, and in each patient folder contains 3D images named "patientXXX_frameYY" where YY is the slice index the image starts from. If you are using a different dataset, you'll have to adapt that piece of code to your dataset.
