### ISSUE TITLE
The result of the test code segmentation image is blank or noisy.

### ISSUE THREAD

**Issue by Max-Well-Wang** [sunjesse/shape-attentive-unet#9]
Hello, dear author, when I run the test with the saved model (training accuracy: 0.94, Val IOU: [0.83, 0.79, 0.89]), the output prediction result is some noise.I don't know what caused this error，I look forward to your tips. thank you! 

Wrong location：line:122 in test_ and_ pack.py file
**# forward pass
p1 = sm(slice_ data, epoch=0, segSize=True, return_ att=args.attention_ map)
_,  pred = torch.max(p1, dim=1)**
#Display picture
img = np.transpose(as_ numpy(pred.cpu()), (1, 2, 0)) 
plt.imshow(img[:,:,0])
plt.show()   # Show Noise

**Comment by sunjesse** [comment]
Hi,

I recommend using the visualize_result function in test_and_pack.py file, that will correctly post-process the image so it can be displayed correctly. One reason why I think your current code is displaying blank or noise is because the img array contains values only from 0 to 3 (the class indices). You'll have to multiply that array by 85 (255/3) to get an image that is within the typical grayscale domain.

**Comment by Max-Well-Wang** [comment]
Hi,

I used the visualize_result function in test_and_pack.py file and the latest files (test.py). I finally made it! thank you very much!!
